title: Feng, Shiqian(Ivy) # your name (or website title) here
logo: "/images/8ba6b8c425a33d45f18d97ac4371c0c.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Shiqian Feng(Ivy) is a postgraduate student studying at HKU, majoring in Data Science. 
  Her research interest lies in the applications of Machine Learning and Deep Learning in Financial Data.
  
  <br><br>
  She likes epic music and Lana Del Rey. 
  See more of her information in her LinkedIn profile!
  
  <br><br>
  <a href="https://hk.linkedin.com/in/shiqian-feng-41b938205">View My LinkedIn Profile Here!</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
